src/main/java/com/foru/freebe/errors/errorcode/CommonErrorCode.java
src/main/java/com/foru/freebe/errors/errorcode/ErrorCode.java
src/main/java/com/foru/freebe/errors/exception/RestApiException.java
src/main/java/com/foru/freebe/errors/handler/GlobalExceptionHandler.java
src/main/java/com/foru/freebe/errors/response/ErrorResponse.java

- ErrorCode (Interface)
- CommonErrorCode
- ErrorResponse
- RestApiException
- GlobalExceptionHandler
ErrorCode를 기반으로 앞으로 있을 도메인 별로 Error를 커스텀할 계획입니다. CommonErrorCode의 경우 Invalid_Parameter, Internal_Server_Error와 같은 일반적인 Error를 담고 있습니다. 이와 같이 MemberErrorCode, ProductErrorCode 이런식으로 확장하면 좋을 것 같습니다.
RestApiException의 경우, 공통된 인터페이스 ErrorCode를 통해 다양한 오류 코드를 캡슐화하고 이를 통해 모든 예외를 통합적으로 처리합니다. 그리고 예외처리를 RestApiException 클래스로 추상화하면 향후 새로운 오류 코드를 추가하거나 비즈니스 로직에 맞춰 예외 처리 로직을 변경할 때 코드의 수정에 용이하게 위함입니다.
ErrorResponse는 error를 응답하는 클래스이고 내부에 정의되어 있는 errors 필드는 바인딩 에러와 같은 유효성 검사 에러를 처리하고, 응답 데이터에서 필드가 비어있을 경우 JSON에서 생략하기 위해 '@JsonInclude(JsonInclude.Include.NON_EMPTY)'를 사용하였습니다.
그리고 가장 중요한 GlobalExceptionHandler는 우리가 앞으로 타겟할 에러들을 커스텀해서 대응하기 위해 만든 클래스입니다. 즉, 에러 핸들링하기 위한 클래스입니다. 저희 서비스 …

[FU-131] 에러 핸들링 base 코드 구현

---

src/main/java/com/foru/freebe/config/CorsConfig.java

https://www.freebe.co.kr과 http://localhost:3000에 대한 CORS 설정
- CORS 설정에는 jwtAuthenticationFilter 앞단에 CORS Filter를 추가하는 방식과 CorsConfigurationSource를 빈으로 등록하는 방식 두 가지가 있는데 어떤 방식이 더 적합할지에 대한 고민이 있었습니다. filter로 추가하게 되면 Spring MVC 레벨에서 제어가 가능하며, 빈으로 등록하게 되면 Spring Security와 Spring MVC에서 전역적으로 CORS를 설정할 수 있다는 차이가 있습니다. 일관된 CORS 처리와 추후 좀 더 세부적인 CORS 설정이 필요해질 수 있음을 고려하여 CorsConfigurationSource를 빈으로 등록하여 사용하기로 결정했습니다🤓
시급도 보통

[FU-132] Cors Configuration

---

src/main/java/com/foru/freebe/config/CorsConfig.java
src/main/java/com/foru/freebe/config/CustomAccessDeniedHandler.java
src/main/java/com/foru/freebe/config/SecurityConfig.java
src/main/java/com/foru/freebe/errors/handler/GlobalExceptionHandler.java
src/main/java/com/foru/freebe/jwt/filter/JwtAuthenticationFilter.java
src/main/java/com/foru/freebe/member/entity/Member.java

**Issue 1**. SqlExceptionHelper   : Data truncated for column 'role' at row 1
**Issue 2.** 사진의뢰자 측에서 사진작가 상품 목록 및 상품 상세를 조회하고자 할 때 403 에러 반환
<br>
**Issue 1**. 
Member 테이블의 Role 컬럼에 들어가는 enum 상수명을 PENDING -> PHOTOGRAPHER_PENDING으로 바꾸면서 DB truncation 이슈가 발생했습니다. 기존에 PENDING으로 엔티티를 생성했을 때 설정된 DB 컬럼 길이보다 PHOTOGRAPHER_PENDING의 길이가 더 길어지면서 발생한 이슈로 보입니다. 
**Issue 2.**
사진작가 상품 목록 및 상품 상세 조회는 별다른 권한 없이도 접근이 가능해야 하는데 CUSTOMER 롤을 부여받은 유저만 접근할 수 있도록 설정되어 있었습니다. 또한 Authorization 헤더 없이 요청을 보내게 되므로 jwt authentication filter에서도 제외되어야 하는데 해당 경로가 제외목록에 포함되어있지 않았습니다.
<br>
**Issue 1.**
Member 테이블의 Role 컬럼 길이를 명시적으로 지정하였습니다. PHOTOGRAPHER_PENDING보다 긴 컬럼명은 앞으로 사용할 일이 없을 것 같아 최대 컬럼 길이는 PHOTOGRAPHER_PENDING에 맞춰 VARCHAR(20)으로 지정하였습니다.
**Issue 2.**
사진작가 상품 목록 및 상품 상세 조회의 경우 로그인이 이뤄지기 전에 접근하는 페이지이므로, 접근권한이 CUSTOMER로 …

[FU-196] 로그인 과정에서 발생하는 버그 픽스

---

src/main/java/com/foru/freebe/errors/errorcode/CommonErrorCode.java
src/main/java/com/foru/freebe/profile/Controller/CustomerProfileController.java
src/main/java/com/foru/freebe/profile/dto/LinkInfo.java
src/main/java/com/foru/freebe/profile/dto/ProfileResponse.java
src/main/java/com/foru/freebe/profile/entity/Link.java
src/main/java/com/foru/freebe/profile/entity/Profile.java
src/main/java/com/foru/freebe/profile/repository/LinkRepository.java
src/main/java/com/foru/freebe/profile/repository/ProfileRepository.java
src/main/java/com/foru/freebe/profile/service/ProfileService.java

- Profile entity에 profileImageUrl 필드 추가 
(추후 회원가입 과정에서 profileImageUrl, InstagramId를 등록하는 서비스 로직 추가 예정입니다.)
- Link entity 추가 
- 사진작가 프로필 조회 API 구현
- customer 측에서 필요한 서비스 로직은 이번 PR에 포함되어 있는 로직 하나로 끝일 것 같은데 굳이 ProfileService를 Customer, Photographer로 구분하는 게 좋은 판단인지 고민입니다..🥲
(의견을 남겨주시면 감사하겠습니다!)
- 이어서 작업할 테스크는 없는 관계로 시급도는 낮습니다!
- ProfileService 클래스 리뷰 부탁드립니다!

[FU-181] 사진의뢰자 측에서 사진작가 프로필을 조회하는 API 구현

---

build.gradle
src/main/java/com/foru/freebe/S3ImageService.java
src/main/java/com/foru/freebe/common/service/S3ImageService.java
src/main/java/com/foru/freebe/config/S3Config.java
src/main/java/com/foru/freebe/errors/errorcode/AwsErrorCode.java
src/main/java/com/foru/freebe/errors/errorcode/CommonErrorCode.java
src/main/java/com/foru/freebe/errors/errorcode/ImageErrorCode.java
src/main/java/com/foru/freebe/product/controller/PhotographerProductController.java
src/main/java/com/foru/freebe/product/dto/photographer/ProductRegisterRequest.java
src/main/java/com/foru/freebe/product/dto/photographer/RegisteredProductResponse.java
src/main/java/com/foru/freebe/product/entity/ProductImage.java
src/main/java/com/foru/freebe/product/service/PhotographerProductService.java
src/main/java/com/foru/freebe/reservation/controller/CustomerReservationController.java
src/main/java/com/foru/freebe/reservation/dto/FormDetailsViewResponse.java
src/main/java/com/foru/freebe/reservation/dto/FormRegisterRequest.java
src/main/java/com/foru/freebe/reservation/dto/PhotoOption.java
src/main/java/com/foru/freebe/reservation/dto/ReferenceImageUrls.java
src/main/java/com/foru/freebe/reservation/entity/ReferenceImage.java
src/main/java/com/foru/freebe/reservation/entity/ReservationForm.java
src/main/java/com/foru/freebe/reservation/repository/ReferenceImageRepository.java
src/main/java/com/foru/freebe/reservation/service/CustomerReservationService.java
src/main/java/com/foru/freebe/reservation/service/PhotographerReservationService.java
src/main/resources/application.yaml

- Thumbnailator를 사용한 이미지 리사이즈 로직 구현
- S3와 연동하여 버킷내에 /origin, /thumbnail 경로에 각각 이미지 업로드 로직 구현
- 위 내용은 신청서 상세보기, 예약신청서 등록, 상품 등록 API에 관련된 코드 리팩터링
- 해당 API에 대한 API Docs 업데이트, 프론트 개발 시 참고부탁드립니다!
- 기존의 ReferenceImage Entity에 preferredImage 필드를 origin_url, thumbnail_url 필드로 수정하여 리팩터링
- 생각한 것보다 리팩터링 해야 할 부분이 많고 많은 에러들 때문에 PR이 조금 지연되었습니다...ㅠㅠ🙇‍♂️
- 이미지 리사이즈 레퍼런스를 보면서 이미지의 확장자에 대한 validation을 진행하는 코드를 활용하여 작성했을 때 에러가 났고, 해당 에러에 대한 수정이 어려워 지금은 validation을 하지 않고 있습니다. 사실 아직까지는 확장자에 대한 범위를 제한하고 있지 않아서 추후에 사용자 요구사항에 따라 다시 추가할 의향이 있습니다😊
- 이미지 리사이즈 과정에서 (A) **원본 이미지에 대한 이미지 비율에 따른 축소**, (B) **특정 너비, 높이 픽셀을 정한 것에 맞게 이미지를 축소**를 고민하고 있었고, 저희 기획에 따라 (B) 방법을 채택하여 코드 작성을 하였지만 추후에 사용자가 썸네일 이미지에 대한 품질이 낮다고 평가할 우려가 있습니다. 해당 부분 인지하여 추후에 피드백을 받는다면 추가로 품질을 높이는 코드를 추가할 계획입니다.
- 시급도는 중간입니다. …

[FU-126] 이미지 업로드 및 리사이즈 로직 구현

---

src/main/java/com/foru/freebe/constants/SortConstants.java
src/main/java/com/foru/freebe/reservation/dto/FormComponent.java
src/main/java/com/foru/freebe/reservation/entity/ReservationForm.java
src/main/java/com/foru/freebe/reservation/service/PhotographerReservationService.java

- 신청서 리스트뷰 조회 시, 각 신청서 컴포넌트마다 `reservationID`도 함께 반환하여 이후 신청서상세보기 페이지와 연결이 가능하도록 수정
- 신청서 리스트뷰 조회 시, 신청서 상태 별로 정렬이 이뤄진 상태에서 응답하도록 수정
```
{
"status": 200,
"message": "Successfully get reservation list",
"data": [
{
"reservationStatus": "WAITING_FOR_PHOTO",
"formComponent": [
{
"reservationId": 17,
"reservationSubmissionDate": "2024-09-04",
"reservationStatus": "WAITING_FOR_PHOTO",
"customerName": "이유리",
"productTitle": "웨딩스냅1",
"shootingDate": {
"date": "2024-08-30",
"startTime": "15:00:00",
"endTime": "17:00:00"
}
},
{
"reservationId": 18,
"reservationSubmissionDate": "2024-09-04",
"reservationStatus": "WAITING_FOR_PHOTO",
"customerName": "이유리",
"productTitle": "웨딩스냅1",
"shootingDate": {
"date": "2024-09-01",
"startTime": "14:00:00",
"endTime": "17:00:00"
}
},
{
"reservationId": 14, …
```

[FU-199] 신청서 리스트뷰 조회 API 보완

---

src/main/java/com/foru/freebe/config/CustomLogoutHandler.java
src/main/java/com/foru/freebe/config/SecurityConfig.java
src/main/java/com/foru/freebe/errors/errorcode/CommonErrorCode.java
src/main/java/com/foru/freebe/errors/errorcode/JwtErrorCode.java
src/main/java/com/foru/freebe/jwt/filter/JwtAuthenticationFilter.java
src/main/java/com/foru/freebe/jwt/filter/JwtExceptionFilter.java
src/main/java/com/foru/freebe/jwt/model/JwtToken.java
src/main/java/com/foru/freebe/jwt/repository/JwtTokenRepository.java
src/main/java/com/foru/freebe/jwt/service/JwtProvider.java
src/main/java/com/foru/freebe/jwt/service/JwtService.java
src/main/java/com/foru/freebe/jwt/service/JwtVerifier.java

1. 로그아웃 요청 시, 요청헤더에 실려온 리프레시 토큰을 무효화시키는 로직을 구현했습니다.
2. 토큰의 무효화 여부를 기록할 수 있도록 DB의 리프레시토큰 저장소에 isRevoked 컬럼을 추가했습니다.
3. 매 API 요청 마다 엑세스토큰을 검증하는 로직에 아래 절차가 추가되었습니다.
-> 요청헤더에 실려온 엑세스토큰의 페이로드에 담긴 정보를 통해 DB에서 동일한 사용자의 리프레시 토큰을 조회하고, 리프레시 토큰의 무효화 여부를 검증합니다.
- 토큰의 무효화 로직 구현방식을 고민했습니다. 
1. 토큰 저장소에 무효화 여부를 기록하기 위한 컬럼을 추가
2. 무효화된 토큰을 저장하기 위한 Black List 테이블을 추가로 설계
3. Redis를 사용해서 블랙리스트를 관리
우선 (3)의 경우 사용자가 많지 않은 초기단계에 Redis를 사용하면서 얻는 이점보다는 관리 측면의 오버헤드가 늘어나는 단점이 더 크다고 판단해 배제하였습니다. 추후에 성능 개선의 뚜렷한 이유가 생길때 도입을 검토해보면 좋을 것 같습니다 :)
그리고 리프레시토큰 저장소 이외에 블랙리스트를 저장하기 위한 테이블을 추가로 설계하는 방식 (2)의 경우, 토큰이 만료되면 배치잡을 통해 리프레시토큰 저장소와 블랙리스트 양측에서 만료된 토큰을 제거해야하기 때문에 큰 이점을 느끼지 못했습니다. 따라서 첫번째 방식으로 컬럼을 통해 토큰 무효화 여부를 기록하고자 합니다~! 이 경우에도 배치잡으로 만료된토큰을 주기적으로 제거해줘야해서 배치 작업용 코드가 필요할 것 같네요 .. (쓰다보니 생각남😅)
<br>
- jwtProvider, jwtService …

[FU-133] 로그아웃 로직 구현

---

src/main/java/com/foru/freebe/auth/controller/AuthController.java
src/main/java/com/foru/freebe/auth/dto/LoginRequest.java
src/main/java/com/foru/freebe/member/entity/Role.java
src/main/java/com/foru/freebe/reservation/controller/PhotographerReservationController.java
src/main/java/com/foru/freebe/reservation/dto/FormDetailsViewResponse.java
src/main/java/com/foru/freebe/reservation/dto/ReservationStatusUpdateRequest.java
src/main/java/com/foru/freebe/reservation/entity/ReservationForm.java
src/main/java/com/foru/freebe/reservation/entity/ReservationHistory.java
src/main/java/com/foru/freebe/reservation/entity/ReservationStatus.java
src/main/java/com/foru/freebe/reservation/service/CustomerReservationService.java
src/main/java/com/foru/freebe/reservation/service/PhotographerReservationDetails.java
src/main/java/com/foru/freebe/reservation/service/PhotographerReservationService.java

1.  신청서 상태를 변경하기 위한 API 개발
- NEW -> IN_PROGRESS, CANCELLED
- IN_PROGRESS -> WAITING_FOR_DEPOSIT, CANCELLED
- WAITING_FOR_DEPOSIT -> WAITING_FOR_PHOTO, CANCELLED
- WAITING_FOR_PHOTO -> PHOTO_COMPLETED, CANCELLED
2. 사진작가측 신청서 상세보기 페이지 조회 API 보완
-> 신청서 상세조회 시, 사진작가측 메모와 고객이 선택한 옵션 정보를 response body에 포함하였음
새 신청, 상담 중, 입금 대기, 촬영 대기 각각의 상태마다 다음 상태로 넘어가기 위한 로직과 신청서를 드롭할 수 있는 로직의 구현이 필요했습니다. 이때 신청서를 드롭할 수 있는 모든 케이스를 고려하여 `REJECTED`, `FAILED_CONSULTATION`, `DEPOSIT_NOT_RECEIVED`, `NO_SHOW` 등의 상태 변경을 위한 버튼이 모두 필요한지에 대한 고민이 있었는데, 실제 유저 피드백에 따라 상태가 추가/변경될 경우 UI도 함께 수정되어야 하는 불편함이 있을 것이라 생각되었습니다. 따라서 모든 신청서 상태마다 확인/취소 버튼 두개만을 가지고, 신청서 취소를 할때는 취소 사유를 유저가 직접 기입할 수 있도록 해서 이후의 확장성, 변동가능성을 열어두는 방식을 선택했습니다! (같이 의논해줘서 고마워 😇) 
- 시급도 높음: 다른 개발티켓과의 결합도가 높지 않지만, 이번 스프린트 안에는 머지되어야 해서 시급도 높음입니다 .. 🤣
- 취소된 신청서를 다시 …

[FU-123] 신청서 상태변경 API

---

src/main/java/com/foru/freebe/auth/dto/LoginRequest.java
src/main/java/com/foru/freebe/auth/model/KakaoUser.java
src/main/java/com/foru/freebe/errors/handler/GlobalExceptionHandler.java
src/main/java/com/foru/freebe/member/entity/Member.java
src/main/java/com/foru/freebe/product/controller/PhotographerProductController.java
src/main/java/com/foru/freebe/product/dto/customer/ProductDetailResponse.java
src/main/java/com/foru/freebe/product/dto/customer/ProductListResponse.java
src/main/java/com/foru/freebe/product/dto/photographer/ProductComponentDto.java
src/main/java/com/foru/freebe/product/dto/photographer/ProductDiscountDto.java
src/main/java/com/foru/freebe/product/dto/photographer/ProductOptionDto.java
src/main/java/com/foru/freebe/product/dto/photographer/ProductRegisterRequest.java
src/main/java/com/foru/freebe/product/dto/photographer/RegisteredProductResponse.java
src/main/java/com/foru/freebe/product/dto/photographer/UpdateProductRequest.java
src/main/java/com/foru/freebe/product/service/PhotographerProductService.java
src/main/java/com/foru/freebe/reservation/dto/BasicReservationInfoResponse.java
src/main/java/com/foru/freebe/reservation/dto/CustomerDetails.java
src/main/java/com/foru/freebe/reservation/dto/FormComponent.java
src/main/java/com/foru/freebe/reservation/dto/FormDetailsViewResponse.java
src/main/java/com/foru/freebe/reservation/dto/FormListViewResponse.java
src/main/java/com/foru/freebe/reservation/dto/FormRegisterRequest.java
src/main/java/com/foru/freebe/reservation/dto/PhotoOption.java
src/main/java/com/foru/freebe/reservation/dto/PreferredDate.java
src/main/java/com/foru/freebe/reservation/dto/ReservationInfoResponse.java
src/main/java/com/foru/freebe/reservation/dto/StatusHistory.java
src/main/java/com/foru/freebe/reservation/entity/ReferenceImage.java
src/main/java/com/foru/freebe/reservation/repository/ReservationFormRepository.java
src/main/java/com/foru/freebe/reservation/service/CustomerReservationService.java
src/main/java/com/foru/freebe/reservation/service/PhotographerReservationDetails.java
src/main/java/com/foru/freebe/reservation/service/PhotographerReservationService.java
src/main/resources/application.yaml

- DTO 필드에 대한 유효성 검증을 추가했습니다. 
- 프론트엔드의 작업 내용에 맞춰(FU-157) Request DTO의 최대 글자수 제한을 적용했습니다.
- 사진작가측 상품목록 조회 시 예약체결 건수를 조회하는 로직을 구현했습니다. (TODO 사항이었는데 구현되지 않고 있었음..)
- 의뢰자측 신청서 조회 ReponseBody에서 약관 동의여부를 삭제했습니다. (기존에 논의했던 내용, [API Docs](https://www.notion.so/yul-lee/customer-reservation-reservationFormI-ed0439b036b14ab582cb675cb57c331a?pvs=4) 참고)
🙅‍♀️
적절하게 검증되고 있는지 확인 부탁드립니다! 시급도는 낮음, 예상 리뷰시간은 5분 미만입니다.

[FU-202] DTO 필드 유효성 검증 적용

---

.github/workflows/cd_workflow_dev.yml
src/main/java/com/foru/freebe/common/service/S3ImageService.java
src/main/java/com/foru/freebe/config/S3Config.java
src/main/java/com/foru/freebe/member/controller/JoinController.java
src/main/java/com/foru/freebe/member/service/MemberService.java
src/main/java/com/foru/freebe/product/service/PhotographerProductService.java
src/main/java/com/foru/freebe/profile/entity/Profile.java
src/main/java/com/foru/freebe/profile/entity/ProfileImage.java
src/main/java/com/foru/freebe/profile/repository/ProfileImageRepository.java
src/main/java/com/foru/freebe/profile/repository/ProfileRepository.java
src/main/java/com/foru/freebe/profile/service/ProfileService.java
src/main/java/com/foru/freebe/reservation/controller/CustomerReservationController.java
src/main/java/com/foru/freebe/reservation/service/CustomerReservationService.java
src/main/java/com/foru/freebe/s3/S3ImageService.java
src/main/java/com/foru/freebe/s3/S3ImageType.java
src/main/resources/application.yaml

- 사진작가 회원가입 페이지에서 필요한 API 개발을 완료했습니다.
- 프로필 이미지 등록하는 로직을 구현했습니다. ProfileImage 테이블이 새로 추가되었습니다.
- S3 이미지 업로드 경로를 구체화했습니다.
1. 상품사진 등록: photograpers/{photographerId}/products/{파일명}
2. 프로필사진 등록: photographers/{photographerId}/profile/{파일명}
3. 레퍼런스 이미지 등록: customers/{customerId}/reservations/{파일명}
- 코드 상에서 @Value 어노테이션을 사용해 환경변수를 읽어올 때 기존에는 .properties에 등록된 환경변수를 참조했지만, AWS 관련 환경변수가 많아지고 계층을 나눌 필요성이 있다고 판단해 .yml파일의 계층적 구조를 사용하기로 했습니다. 
- S3에 서로 다른 이미지를 업로드할 때 만약 파일명이 중복된다면 덮어쓰기 되면서 기존의 파일을 잃게되거나, 혹은 업로드 시 에러가 날 수 있음을 고려했습니다. 따라서 이미지 업로드 시에 고유한 파일명을 보장하기 위해 `랜덤스트링+파일명`으로 저장되게끔 구현했습니다. 
- 로그인 버그픽스 티켓의 시급도가 높아 해당 티켓의 테스트코드 작성은 FU-124에서 함께 처리할 예정입니다.
- @yuseok0215 가독성 문제로 인해 cd_workflow_dev.yml파일에 환경변수 등록 시, .properties파일과 환경변수 위치를 맞추는게 어떨까 하는 생각이 들었습니당 🙇‍♀️
시급도 (보통)
작성한 코드가 많지는 않아서 전반적으로 검토 …

[FU-179] 사진작가 회원가입 API 개발

---

src/main/java/com/foru/freebe/auth/controller/AuthController.java
src/main/java/com/foru/freebe/auth/dto/LoginResponse.java
src/main/java/com/foru/freebe/common/dto/ResponseBody.java
src/main/java/com/foru/freebe/config/SecurityConfig.java
src/main/java/com/foru/freebe/jwt/filter/JwtAuthenticationFilter.java
src/main/java/com/foru/freebe/member/controller/JoinController.java
src/main/java/com/foru/freebe/member/service/MemberService.java
src/main/java/com/foru/freebe/product/controller/CustomerProductController.java
src/main/java/com/foru/freebe/product/controller/PhotographerProductController.java
src/main/java/com/foru/freebe/product/respository/ProductRepository.java
src/main/java/com/foru/freebe/product/service/CustomerProductService.java
src/main/java/com/foru/freebe/product/service/PhotographerProductService.java
src/main/java/com/foru/freebe/profile/Controller/CustomerProfileController.java
src/main/java/com/foru/freebe/profile/Controller/PhotographerProfileController.java
src/main/java/com/foru/freebe/profile/dto/UpdateProfileRequest.java
src/main/java/com/foru/freebe/profile/repository/ProfileImageRepository.java
src/main/java/com/foru/freebe/profile/service/ProfileService.java
src/main/java/com/foru/freebe/reservation/controller/CustomerReservationController.java
src/main/java/com/foru/freebe/reservation/controller/PhotographerReservationController.java
src/main/java/com/foru/freebe/reservation/service/CustomerReservationService.java
src/main/java/com/foru/freebe/reservation/service/PhotographerReservationDetails.java
src/main/java/com/foru/freebe/reservation/service/PhotographerReservationService.java
src/test/java/com/foru/freebe/profile/service/ProfileServiceTest.java

- Service Layer에서는 단순히 로직이 수행된 후 결과값을 반환하게 수정했습니다.
- Service Layer에서 ResponseBody로 반환하지 않는 이유는 비즈니스 로직을 담는 레이어의 역할을 명확하게 하기 위함과 테스트코드 작성 시 불필요한 코드 또한 예방할 수 있습니다.
- Controller Layer에서는 Service Layer에서 수행 후 반환한 값을 ResponseBody에 싣고 ResponseEntity로 감싸서 응답하도록 수정했습니다.  
- 로컬에서의 전체 API 테스트 수행 (모든 API 통과, [API Docs](https://www.notion.so/yul-lee/API-Docs-9db17cb3aa3842a68edcdafa651a347b)에 통과된 API 표시)
- 테스트를 진행하면서 통과하지 못한 테스트를 기준으로 코드 추가 및 리팩터링 수행
- "/customer/profile/**" 경로에 대한 접근 및 토큰 권한 추가
- 상품 등록, 예약신청서 등록 시 member(사진작가)에 대한 검증 로직 추가
- 변경된 코드 또한 리팩터링
- 부가적인 오류 수정\
- 기존의 memberService.findOrRegisterMember() 내부에 있는 setResponseBody()를 활용해서 Service Layer에서 ResponseBody를 정의하고 있습니다. 만약 현재 변경하고자 하는 방식으로 대입해본다면 memberService.findOrRegisterMember()는 headers와 member의 RoleType을 반환하면 …

[FU-201] ResponseEntity<ResponseBody<T>>으로 responseType 변경

---

.github/workflows/cd_workflow_dev.yml
scripts/start.sh
scripts/stop.sh
src/main/resources/application.yaml

Code Deploy를 통한 배포 자동화가 제대로 이루어지지 않는 문제가 빈번하게 발생하고 있음.
</br>
**배포 실패 로그**
The overall deployment failed because too many individual instances failed deployment, too few healthy instances are available for deployment, or some instances in your deployment group are experiencing problems.
**상세 로그**
scripts/stop.sh
Script at specified location: scripts/stop.sh run as user root failed with exit code 1
<br>
Aws CodeDeploy에서 Event Hook에 대한 로그를 확인해 봤을때, 전체 라이프 사이클 중 `After Install` 단계에서 배포가 실패하고 있음을 확인할 수 있다.
</br>
`After Install` 단계는 이번 배포에 해당하는 어플리케이션을 실행하기 직전에 이뤄지며, appspec.yml을 살펴보면 우리 서비스에서는 stop.sh을 실행하는 단계에 해당한다. Code Deploy의 상세 로그에서도 stop.sh을 실행하는 중에 배포가 실패했음을 알려주고 있다. 
```
hooks:
AfterInstall:
- location: scripts/stop.sh
timeout: 60
runas : root
```
</br>
stop.sh 스크립트는 아래와 같고, 새 어플리케이션을 …

[FU-228] CodeDeploy 배포 자동화 오류 분석 및 문제해결을 위한 스크립트 개선

---

src/main/java/com/foru/freebe/auth/controller/AuthController.java
src/main/java/com/foru/freebe/auth/dto/LoginResponse.java
src/main/java/com/foru/freebe/common/dto/ImageLinkSet.java
src/main/java/com/foru/freebe/errors/errorcode/ProfileErrorCode.java
src/main/java/com/foru/freebe/member/controller/JoinController.java
src/main/java/com/foru/freebe/member/dto/PhotographerJoinRequest.java
src/main/java/com/foru/freebe/member/service/MemberService.java
src/main/java/com/foru/freebe/product/controller/CustomerProductController.java
src/main/java/com/foru/freebe/product/service/CustomerProductService.java
src/main/java/com/foru/freebe/product/service/PhotographerProductService.java
src/main/java/com/foru/freebe/profile/Controller/CustomerProfileController.java
src/main/java/com/foru/freebe/profile/Controller/PhotographerProfileController.java
src/main/java/com/foru/freebe/profile/dto/ProfileResponse.java
src/main/java/com/foru/freebe/profile/dto/UpdateProfileRequest.java
src/main/java/com/foru/freebe/profile/entity/Profile.java
src/main/java/com/foru/freebe/profile/entity/ProfileImage.java
src/main/java/com/foru/freebe/profile/repository/ProfileImageRepository.java
src/main/java/com/foru/freebe/profile/repository/ProfileRepository.java
src/main/java/com/foru/freebe/profile/service/ProfileService.java
src/main/java/com/foru/freebe/reservation/controller/CustomerReservationController.java
src/main/java/com/foru/freebe/reservation/dto/BasicReservationInfoResponse.java
src/main/java/com/foru/freebe/reservation/dto/FormRegisterRequest.java
src/main/java/com/foru/freebe/reservation/service/CustomerReservationService.java
src/main/java/com/foru/freebe/reservation/service/ReservationVerifier.java
src/main/java/com/foru/freebe/s3/S3ImageService.java
src/test/java/com/foru/freebe/profile/service/ProfileServiceTest.java
src/test/java/com/foru/freebe/reservation/service/ReservationServiceTest.java

- 사진작가 고유 url 생성 방식이 변경되었습니다.
- 기존: 랜덤스트링으로 고유 url 생성
- 변경: 회원가입 시점에 profileName을 입력받아 프로필명으로 고유 url 생성
- 사진작가 회원가입 시점에 입력받는 profileName의 중복여부 검사 로직이 추가되었습니다.
- 사진작가 회원가입 시점에 프로필 이미지를 등록하는 로직이 제거되었습니다. 
- 프로필 관리 페이지에서 프로필 이미지 등록/수정이 가능해졌습니다.
- 사진작가 프로필 관리 페이지에서 배너 이미지 등록/수정 로직이 추가되었습니다. 
- 기존에는 multiFile이 아닌 url로 request 들어오던 것을 multiFile로 받아 s3에 이미지 업로드합니다.
- 회원가입, 프로필 로직이 다소 수정되면서 ProfileServiceTest 코드의 리팩토링이 필요해졌습니다 ㅜ 해당 pr 머지된 이후에 바로 pull 받아서 테스트코드 수정 이어나갈 예정입니다!

[FU-256] 사진작가 회원가입/프로필 관리 로직 업데이트

---

src/main/java/com/foru/freebe/profile/Controller/PhotographerProfileController.java
src/main/java/com/foru/freebe/profile/service/ProfileService.java
src/main/java/com/foru/freebe/s3/S3ImageService.java
src/test/java/com/foru/freebe/profile/service/ProfileServiceTest.java

- FU-256 티켓에서 사진작가 url 생성/프로필 업데이트 API를 수정하면서 ProfileService 클래스의 구조가 많이 바뀌게 되었습니다. FU-256에서는 배포 테스트가 시급해 테스트코드 수정을 미처 하지 못해서 이번 티켓에서 ProfileService 테스트코드를 리팩터링해 작성했습니다.
- S3에 이미지 업로드하는 경로를 재구성하였습니다.
- S3에 이미지 업데이트 시, 기존 존재하는 이미지는 삭제하는 로직이 추가되었습니다.
- 변경 파일이 많지 않아 전반적인 검토 부탁드려용
- 예상 리뷰시간: 5분
- 시급도: 보통

[FU-257] Profile service 테스트코드 리팩터링

---

.github/workflows/cd_workflow_dev.yml
src/main/java/com/foru/freebe/auth/controller/AuthController.java
src/main/java/com/foru/freebe/auth/service/KakaoAuthService.java
src/main/java/com/foru/freebe/auth/service/KakaoLoginService.java
src/main/java/com/foru/freebe/member/controller/JoinController.java
src/main/java/com/foru/freebe/member/dto/PhotographerJoinRequest.java
src/main/java/com/foru/freebe/member/service/PhotographerJoinService.java
src/main/java/com/foru/freebe/reservation/dto/ReservationStatusUpdateRequest.java
src/test/java/com/foru/freebe/member/service/PhotographerJoinServiceTest.java
src/test/java/com/foru/freebe/profile/service/ProfileServiceTest.java
src/test/java/com/foru/freebe/reservation/service/ReservationServiceTest.java

</br>
- 미뤄뒀던 레거시 코드에 대한 테스트 코드 작성 태스크를 완료했습니다.
- 사진작가측 신청서 상태변경 서비스 로직에 대한 테스트 코드 작성
- 사진작가측 회원가입 로직에 대한 테스트 코드 작성
- 회원가입 로직에 대한 테스트 코드를 작성하다보니, 관련 클래스들의 책임을 명확하게 구분할 필요성을 느껴 리팩터링을 진행했습니다.
- 회원가입 서비스로직을 담당하는 클래스명 리팩터링
- 기존: MemberService
- 변경: PhotographerJoinService
- 로그인 로직을 담당하는 클래스명 리팩터링
- 기존: AuthService
- 변경: KakaoLoginService
- 카카오 인증 서버와 통신을 담당하는 로직은 새로운 클래스로 추출
- 기존: AuthService
- 변경: KakaoAuthService
</br>
- 회원가입/로그인 로직에 대해서는 롤백 테스트도 함께 진행하면 좋겠다는 생각이 들었는데, 이번 스프린트에서 해야 할 일이 많아 기본적인 테스트코드만 작성했습니다 😓
</br>
- 특별한 리뷰 요청사항은 없습니다.
- 시급도 낮음입니다. 이번 스프린트 내에만 완료되면 될 것 같아요!

[FU-124] 신청서 상태변경 & 회원가입 API 테스트코드 작성

---

src/main/java/com/foru/freebe/product/respository/ProductRepository.java
src/main/java/com/foru/freebe/product/service/CustomerProductService.java
src/main/java/com/foru/freebe/product/service/PhotographerProductService.java
src/main/java/com/foru/freebe/product/service/ProductDetailConvertor.java
src/main/java/com/foru/freebe/reservation/controller/PhotographerReservationController.java
src/main/java/com/foru/freebe/reservation/dto/PastReservationFormComponent.java
src/main/java/com/foru/freebe/reservation/dto/PastReservationResponse.java
src/main/java/com/foru/freebe/reservation/repository/ReservationFormRepository.java
src/main/java/com/foru/freebe/reservation/service/PhotographerPastReservationService.java

- 지난 예약 목록을 조회할 수 있는 기능을 개발했습니다.
- 조회 시 `검색 키워드`, `기간`, `신청서 상태`를 필터링할 수 있습니다. (쿼리파라미터 이용)
- @eujin-shin ResponseBody 형식이 다소 변경되었습니다.
```
{
"message": "Successfully get reservation list",
"data": {
"totalPages": 4,
"pastReservationFormComponent": [
{
"reservationStatus": "CANCELLED_BY_PHOTOGRAPHER",
"reservationId": 1,
"reservationSubmissionDate": "2024-09-30",
"customerName": "이유리",
"productTitle": "야외스냅",
"shootingDate": null,
"price": 210000,
"image": "https://freebe-data.s3.ap-northeast-2.amazonaws.com/photographers/1/products/thumbnail/f76b78a4-c3bf-4943-930f-6fe95693b24a%E1%84%89%E1%85%A1%E1%84%8C%E1%85%B5%E1%86%AB1.png"
},
{
"reservationStatus": "CANCELLED_BY_PHOTOGRAPHER",
"reservationId": 2,
"reservationSubmissionDate": "2024-09-30",
"customerName": "이유리",
"productTitle": "야외스냅", …
```

[FU-215] 지난예약 목록 조회 및 필터링+페이징 기능 구현

---

src/main/java/com/foru/freebe/common/dto/ImageLinkSet.java
src/main/java/com/foru/freebe/common/dto/SingleImageLink.java
src/main/java/com/foru/freebe/member/dto/PhotographerJoinRequest.java
src/main/java/com/foru/freebe/product/service/PhotographerProductService.java
src/main/java/com/foru/freebe/profile/service/ProfileService.java
src/main/java/com/foru/freebe/reservation/controller/CustomerReservationController.java
src/main/java/com/foru/freebe/reservation/dto/FormRegisterRequest.java
src/main/java/com/foru/freebe/reservation/entity/ReferenceImage.java
src/main/java/com/foru/freebe/reservation/service/CustomerReservationService.java
src/main/java/com/foru/freebe/s3/S3ImageService.java
src/test/java/com/foru/freebe/product/service/PhotographerProductServiceTest.java
src/test/java/com/foru/freebe/profile/service/ProfileServiceTest.java

- 레퍼런스 이미지 등록 시 Multipart File과 Existing url을 모두 처리할 수 있도록 로직을 수정했습니다.
- 배너 이미지가 삭제되지 않는 문제를 해결했습니다.
- (유저 권한 부여에 대해서는 내일 작업해서 PR 올라갈 예정입니다!)
- 리팩터링은 내일 새 티켓에서.. ㅜㅜ

[FU-269] 레퍼런스 이미지 Multipart parsing 에러, 배너이미지 삭제 안되는 문제 해결

---

src/main/java/com/foru/freebe/auth/model/KakaoUser.java
src/main/java/com/foru/freebe/auth/service/KakaoAuthService.java
src/main/java/com/foru/freebe/auth/service/KakaoLoginService.java
src/main/java/com/foru/freebe/member/entity/Member.java

1. 그동안 개발 단계에서 카카오 로그인을 테스트용 애플리케이션으로 사용하고 있던 것을 배포용 애플리케이션으로 바꾸기 위해 환경변수 세팅을 완료했습니다. (커밋 이력은 따로 없음)
2. 카카오 로그인 시 선택적 동의로 생년월일, 성별 데이터를 받아올 수 있게끔 코드 보완했습니다.
- 얼마 전 카카오 디벨로퍼스에 개인정보 동의항목 심사 신청 시, 만 14세 이상인지 여부를 자체적으로 판단하기 위해 `생년월일`을 필수 항목으로 하고 개인정보 처리방침 약관에도 생년월일을 필수로 구분했었습니다. 하지만 카카오 배포용 애플리케이션 설정 중에 `간편가입` 기능 활성화를 통해 서비스 약관 동의와 만 14세 이상 연령 동의를 필수로 받을 수 있도록 설정할 수 있음을 알게 되었습니다 🤓
- 따라서 개인정보 처리방침에 생년월일은 `선택적 수집항목`으로 재분류하고 로그인 시점에도 생년월일을 선택항목으로 재설정하게 되었습니다! 
- 사진작가측 회원가입 페이지에서도 만 14세 이상인지 여부를 별도로 체크하도록 하지 않아도 괜찮을 거 같습니다 🙇‍♀️
(시급도) 높음. 프론트엔드에서도 PR에 관련 설정 반영했기 때문에 동시에 병합되어야 할 것 같습니당

[FU-254] 카카오 로그인 배포용 애플리케이션 설정

---

src/main/java/com/foru/freebe/auth/service/KakaoLoginService.java
src/main/java/com/foru/freebe/errors/errorcode/LinkErrorCode.java
src/main/java/com/foru/freebe/errors/errorcode/ProductErrorCode.java
src/main/java/com/foru/freebe/profile/entity/Link.java
src/main/java/com/foru/freebe/profile/service/PhotographerProfileService.java

- 요청 들어온 링크들에서 title, url에 대한 중복체크
- Link entity에 linkOrder 필드를 추가해서 각 링크의 순서를 식별하도록 수정
- 시급도는 높음입니다! (오늘 있을 통합테스트를 위해..!)
- profileService가 분리되면서 conflict 해결하느라 커밋명 양해 부탁드립니다🥲
- PhotographerProfileService 클래스 위주로 확인해주시면 됩니다! 
- 추가로 이미지 업로드 시 multipart/form-data의 인코딩 방식이 적용되면서 많이 길어지는 현상이 있습니다.  이때 변환하는 코드를 작성하는 것은 리소스가 많이 들어가 타입을 TEXT로 변경하는게 좋아보이는데 이 부분에 대해서 의견 남겨주시면 좋을 것 같아요!

[FU-274] 외부링크 업데이트 로직 추가 구현

---

src/main/java/com/foru/freebe/auth/controller/AuthController.java
src/main/java/com/foru/freebe/auth/dto/UnlinkRequest.java
src/main/java/com/foru/freebe/auth/service/KakaoUnlinkService.java
src/main/java/com/foru/freebe/errors/errorcode/AuthErrorCode.java
src/main/java/com/foru/freebe/errors/errorcode/MemberErrorCode.java
src/main/java/com/foru/freebe/member/entity/DeletedMember.java
src/main/java/com/foru/freebe/member/entity/Member.java
src/main/java/com/foru/freebe/member/entity/Role.java
src/main/java/com/foru/freebe/member/repository/DeletedMemberRepository.java
src/main/java/com/foru/freebe/product/service/PhotographerProductService.java
src/main/java/com/foru/freebe/profile/service/PhotographerProfileService.java
src/main/java/com/foru/freebe/profile/service/ProfileService.java
src/main/java/com/foru/freebe/reservation/repository/ReservationFormRepository.java
src/main/java/com/foru/freebe/reservation/service/PhotographerReservationService.java

- Kakao developers에서 제공하는 API 호출을 통해 카카오 OAuth와 연동되어 있는 것을 해제
- 재가입 시 KakaoId 충돌 문제로 인해 기존 Member Entity에서의 KakaoId는 null값으로 업데이트 후, 백업 entity인 DeletedMember에 백업 로직 구현
- 탈퇴하고자 하는 사용자가 사진작가의 경우 profile, product 관련 모든 엔티티 삭제 및 S3에 업로드 된 사진파일 삭제
- 탈퇴하고자 하는 사용자가 사진의뢰자의 경우 백업만 진행
- 테스트 코드에서 에러를 잡을 수 없었지만 API 테스트는 통과했기 때문에 PR을 올렸습니다..! 추후 리팩터링된 코드에 대한 테스트코드 작성 티켓에서 같이 진행하도록 할게요🥲
- 시급도는 보통입니다. 유진이가 회원 탈퇴 쪽 구현하기 전까지 해주면 될 것 같습니다!
- KakaoUnlinkService 클래스 리뷰해주시면 됩니다~!

[FU-249] Kakao OAuth 연결 끊기(회원 탈퇴) API 구현

---

.github/workflows/cd_workflow_dev.yml
src/main/java/com/foru/freebe/auth/dto/UnlinkRequest.java
src/main/java/com/foru/freebe/errors/errorcode/ProfileErrorCode.java
src/main/java/com/foru/freebe/member/dto/PhotographerJoinRequest.java
src/main/java/com/foru/freebe/member/service/PhotographerJoinService.java
src/main/java/com/foru/freebe/product/controller/PhotographerProductController.java
src/main/java/com/foru/freebe/product/dto/photographer/ProductOptionDto.java
src/main/java/com/foru/freebe/product/dto/photographer/ProductTitleResponse.java
src/main/java/com/foru/freebe/product/entity/ProductImage.java
src/main/java/com/foru/freebe/product/service/PhotographerProductService.java
src/main/java/com/foru/freebe/profile/Controller/CustomerProfileController.java
src/main/java/com/foru/freebe/profile/Controller/PhotographerProfileController.java
src/main/java/com/foru/freebe/profile/dto/UpdateProfileRequest.java
src/main/java/com/foru/freebe/profile/entity/Profile.java
src/main/java/com/foru/freebe/profile/entity/ProfileImage.java
src/main/java/com/foru/freebe/profile/service/PhotographerProfileService.java
src/main/java/com/foru/freebe/profile/service/ProfileService.java
src/main/java/com/foru/freebe/reservation/controller/CustomerReservationController.java
src/main/java/com/foru/freebe/reservation/controller/PhotographerReservationController.java
src/main/java/com/foru/freebe/reservation/dto/UpdatePhotographerMemo.java
src/main/java/com/foru/freebe/reservation/dto/UpdatePhotographerMemoRequest.java
src/main/java/com/foru/freebe/reservation/entity/ReferenceImage.java
src/main/java/com/foru/freebe/reservation/entity/ReservationForm.java
src/main/java/com/foru/freebe/reservation/service/PhotographerReservationDetails.java
src/main/java/com/foru/freebe/reservation/service/PhotographerReservationService.java

- 사진작가 회원가입 시 연락처 등록 API 보완
- 신청서에서 사진작가 메모 업데이트 API 구현 (null 값도 가능)
- 프로필 업데이트 API에서 request body에 연락처(contact) 필드 추가
- 이미지 관련 필드에 대한 문자열 제한을 600자로 늘림
- Kakao 앱 키 환경변수 등록
- 신청서에 대한 formId를 경로변수로 받을지, request body를 통해 받을지 고민이 있었습니다. 기존에는 formId를 경로변수로 받고 있었는데(아닌 API도  있습니다.) 그런 경우에 service를 호출할 때 request 객체 이외에 formId에 대한 파라미터를 하나 더 넘겨줘야 한다는 단점이 있었습니다. 그래서 이번 티켓에서는 request body에 reservationFormId를 담아서 service를 호출하게 진행하였는데 @rheeri 의견 남겨주면 좋을 것 같아요! 
(의견이 모이더라도 하나로 통합해서 적용하는 건 추후에 유지보수할 때 진행하는 게 좋을 것 같아요. 기존 API들도 유진이가 수정이 필요하기 때문에...!)
- 시급도 높음! 환경변수 누락 때문에 서버 배포가 안되어 있어서 가능하면 리뷰 바로 부탁드려요!
- 이미지 관련 필드 중 문자열 제한 범위를 늘리지 않은 필드가 있는지 검토 부탁드려요!
- 추가된 로직 중 누락된 예외처리가 있는지 확인 부탁드려요!
- @eujin-shin API Docs에 **작가 회원가입, 프로필 업데이트, 사진작가 메모 업데이트** 3개의 API에서 확인해보고 특이사항 있으면 코멘트 남겨주세요!

[FU-293] 사진작가 메모 등록 및 회원가입 시 연락처 등록 API

---

src/main/java/com/foru/freebe/product/controller/PhotographerProductController.java
src/main/java/com/foru/freebe/product/respository/ProductImageRepository.java
src/main/java/com/foru/freebe/profile/Controller/CustomerProfileController.java
src/main/java/com/foru/freebe/profile/Controller/PhotographerProfileController.java
src/main/java/com/foru/freebe/profile/dto/CustomerViewProfileResponse.java
src/main/java/com/foru/freebe/profile/dto/PhotographerViewProfileResponse.java
src/main/java/com/foru/freebe/profile/service/CustomerProfileService.java
src/main/java/com/foru/freebe/profile/service/PhotographerProfileService.java
src/main/java/com/foru/freebe/profile/service/ProfileService.java
src/main/java/com/foru/freebe/reservation/service/CustomerReservationService.java
src/test/java/com/foru/freebe/member/MemberRepositoryTest.java
src/test/java/com/foru/freebe/member/service/PhotographerJoinServiceTest.java
src/test/java/com/foru/freebe/product/service/PhotographerProductServiceTest.java
src/test/java/com/foru/freebe/profile/service/ProfileServiceTest.java
src/test/java/com/foru/freebe/reservation/service/ReservationServiceTest.java

-  ✅ 불필요한 주석 처리가 없는가?
- 사진작가 측에서 프로필 조회 시 contact 필드 추가
- 상품 상세정보 업데이트 API에서 이미지 파일 없이도 업데이트 가능하도록 수정
- 신청서 등록 API 요청 시 기존의 상품 이미지인 originUrl을 사용하여 ProductImage를 조회하도록 수정
- 로컬 API 테스트 통과🫡
- 기존에 있던 ProfileResponse를 사진작가 측과 사진의뢰자 측에서 조회하는 클래스로 분리해야 했습니다. 이 때 클래스명에 대한 고민을 하다가 결국 '각 사용자 측에서 보여지는 응답 객체'를 기준으로 삼아 PhotographerViewProfileResponse, CustomerViewProfileResponse로 작명했는데 혹시 더 나은 클래스명이 있다면 코멘트 부탁드립니다! (괜찮다면 이대로 진행할게요!)
- 시급도는 높음! 얼른 통합테스트를 해야하기 때문이지요..ㅎㅎ (이게 되어야 이후 신청서 관련 API들을 테스트 할 수 있습니다.)
- 변경된 로직에 이상이 없는지 흐름만 확인 부탁드려요!

[FU-295] 신청서 등록 API 에러 픽스

---

src/main/java/com/foru/freebe/product/dto/customer/ProductDetailResponse.java
src/main/java/com/foru/freebe/product/dto/photographer/ProductRegisterRequest.java
src/main/java/com/foru/freebe/product/dto/photographer/UpdateProductDetailRequest.java
src/main/java/com/foru/freebe/product/entity/Product.java
src/main/java/com/foru/freebe/product/service/PhotographerProductService.java
src/main/java/com/foru/freebe/product/service/ProductDetailConvertor.java
src/main/java/com/foru/freebe/reservation/controller/CustomerReservationController.java
src/main/java/com/foru/freebe/reservation/controller/PhotographerReservationController.java
src/main/java/com/foru/freebe/reservation/dto/BasicReservationInfoResponse.java
src/main/java/com/foru/freebe/reservation/dto/FormDetailsViewResponse.java
src/main/java/com/foru/freebe/reservation/dto/FormRegisterRequest.java
src/main/java/com/foru/freebe/reservation/dto/ReservationInfoResponse.java
src/main/java/com/foru/freebe/reservation/dto/ShootingInfoRequest.java
src/main/java/com/foru/freebe/reservation/entity/ReservationForm.java
src/main/java/com/foru/freebe/reservation/service/CustomerReservationService.java
src/main/java/com/foru/freebe/reservation/service/PhotographerReservationDetails.java
src/main/java/com/foru/freebe/reservation/service/PhotographerReservationService.java

- 사진작가 측
- 상품 등록 API: 기본 촬영장소(basicPlace), 고객 선호장소 작성 가능 여부(allowPreferredPlace) 필드 추가
- 상품 상세 정보 조회 API: 기본 촬영장소, 고객 선호장소 작성 가능 여부 필드 추가
- 상품 상세 정보 변경 API에 기본 촬영장소, 고객 선호장소 작성 가능 여부 필드 추가
- 촬영날 정보(날짜, 장소) 업데이트 API: 새 촬영장소(newShootingPlace) 필드 추가
- 신청서 상세보기 API: 사진의뢰자가 작성한 선호장소(preferredPlace) 필드 추가
- 사진의뢰자 측
- 상품 상세 조회 API: 기본 촬영장소 필드 추가
- 예약신청서 등록 API: 선호장소 필드 추가
- 예약신청서 조회 API: 선호장소 필드, 기본 장소 추가
- 예약신청서 조회 API: 기본 촬영장소 필드 추가
- 시급도 높음! 빠른 출시를 위해.. 시간 될 때 바로 해주시면 빠르게 적용할 수 있을 것 같습니다🥲
- 변경된 API가 많지만 각 볼륨이 적어서 빠진 필드가 있는지만 확인해주시면 좋을 것 같아요!
- @eujin-shin API Docs에 'API 수정됨' 상태로 변경해둔 API들 확인해주면 되고 오류가 있으면 코멘트 부탁드려요!

[FU-300] 촬영 장소 관련한 필드 추가

---

.github/workflows/cd_workflow_dev.yml
.github/workflows/cd_workflow_prod.yml
scripts/start.sh

- gitflow 전략에 맞춰 개발 환경과 프로덕션 환경의 배포 자동화를 분리했습니다.
*hot fix 브랜치는 사용하지 않습니다.
- develop -> release로 병합되는 경우에는 개발 서버로 향하는 code deploy group으로 배포되게끔 하고, release -> master로 병합되는 경우에는 운영 서버로 향하는 code deploy group으로 배포되게끔 했습니다.
(겪었던 에러)
cd_workflow 실행 시, build 과정에서 `Code Deploy로 배포` 프로세스에서 아래와 같은 에러가 발생했습니다.
```
An error occurred (DeploymentGroupNameRequiredException) when calling the CreateDeployment operation: Deployment Group name is missing
Error: Process completed with exit code 254.
```
DeploymentGroupName이 환경변수 세팅 되어있음에도 지속적으로 에러가 발생했고, 에러를 재현하던 중 아래와 같은 하나의 명령어가 줄바꿈 처리 되면서 여러 개의 명령어로 인식되어 발생하는 문제임을 파악했습니다. 따라서 이런 경우에는 명령어의 각 줄 끝에 `\` 백슬래시를 추가해 하나의 명령어로 인식되게끔 하는게 필요했습니다. 
```
aws deploy create-deployment --application-name ${{ secrets.AWS_CODE_DEPLOY_APPLICATION }}
--deployment-config-name …
```

[FU-244] 백엔드 개발인프라 분리 구축 테스트

---

src/main/java/com/foru/freebe/product/respository/ProductRepository.java
src/main/java/com/foru/freebe/reservation/repository/ReservationFormRepository.java
src/main/java/com/foru/freebe/reservation/service/CustomerReservationService.java
src/main/java/com/foru/freebe/reservation/service/PhotographerPastReservationService.java

</br>
1. 지난예약 페이지에서 취소건, 완료건을 선택하지 않고 `전체`로 조회했을 때 취소+완료건이 조회될 수 있도록 수정했습니다.
2. ProductRepository에서 특정 상품을 찾을 때 findByTitle을 사용하지 않고, findByTitleAndMember 등으로 조회할 수 있게 수정했습니다. 기존 방식을 사용할 경우 상품제목이 겹치는 유저가 여러명일 때 sql query 실행 시 unique한 결과를 반환하지 못하는 문제가 있었습니다.
</br>
지난예약 페이지에서 키워드를 포함해 검색할 경우 total pages가 적절하게 반환되지 않는 문제가 있습니다. 로컬환경에서는 이 문제가 재현되지 않고 있어서 해당 PR 병합하여 개발서버에서 테스트 진행해볼 예정입니다.
</br>
(시급도 높음) 개발 서버에서 테스트 필요합니다.

[FU-302] 지난예약건 조회 API 필터링기능 보완

---

.github/workflows/cd_workflow_dev.yml
.github/workflows/cd_workflow_prod.yml
src/main/java/com/foru/freebe/auth/controller/AuthController.java
src/main/java/com/foru/freebe/auth/model/ServiceTerms.java
src/main/java/com/foru/freebe/auth/model/ServiceTermsAgreement.java
src/main/java/com/foru/freebe/auth/service/KakaoAuthService.java
src/main/java/com/foru/freebe/config/CorsConfig.java
src/main/java/com/foru/freebe/member/dto/PhotographerJoinRequest.java
src/main/java/com/foru/freebe/member/entity/MemberTermAgreement.java
src/main/java/com/foru/freebe/member/service/PhotographerJoinService.java
src/main/java/com/foru/freebe/message/dto/MessageSendRequest.java
src/main/java/com/foru/freebe/message/service/MessageSendService.java

- 기존에 [개인 정보 처리방침, 서비스 이용약관, 마케팅 동의여부]와 같은 약관을 회원가입 페이지에서 받아오던 것을 카카오 간편가입 기능에 포함시켜 카카오 로그인 연동 시 약관동의를 받게 되었습니다. 따라서 회원가입 API 요청 시 요청바디에서 약관 동의여부가 빠지게 되었습니다. 
- `개인 정보 처리방침`, `서비스 이용약관`의 경우에는 필수 동의항목이라 동의하지 않으면 카카오 로그인에 성공할 수 없기때문에 DB에 저장된 회원의 경우 해당 항목이 동의되었다고 봐도 무방합니다.
- 다만 `마케팅 동의여부`의 경우에는 선택 항목이므로 동의 여부를 미리 DB에 저장해두어야 추후에 활용이 필요한 상황에서 유용할 것 같다는 판단이 들어 사진작가 회원가입 시점에 카카오 API 서버로 부터 마케팅 동의여부만 받아오는 외부 API를 호출하게 되었습니다.
- 개발 서버에서 CORS 설정이 빠져있어 추가했습니다.
- 새 신청 접수 시, 사진작가에게 발송되는 알림톡 탬플릿을 변경했습니다.
- 기존: (버튼명) `자세히보기`
- 변경후: (버튼명) `자세히 보기`
- 마케팅 동의 여부를 어느 시점에 받아오는 것이 좋을지에 대한 고민이 있었습니다. 사진작가와 고객 양쪽의 마케팅 동의여부를 전부 확인하려면 로그인 API에 해당 로직이 포함되어야 하는데, 마케팅 항목 동의는 카카오 최초 연동 시점에만 이루어지는데 매번 로그인을 할 때마다 카카오 API 서버로부터 요청을 보내 동의 여부를 받아오는게 불필요하다는 판단이 들었습니다. 또한 마케팅 동의 여부를 고객측에 활용하게 될 상황이 있을까라는 생각도 들었기 때문에 사진작가로 가입한 …

[FU-313] UI 변경에 따른 회원가입 API/비즈니스 로직 업데이트

---

src/main/java/com/foru/freebe/errors/errorcode/AwsErrorCode.java
src/main/java/com/foru/freebe/errors/errorcode/CommonErrorCode.java
src/main/java/com/foru/freebe/errors/errorcode/LinkErrorCode.java
src/main/java/com/foru/freebe/errors/errorcode/MemberErrorCode.java
src/main/java/com/foru/freebe/errors/errorcode/NoticeErrorCode.java
src/main/java/com/foru/freebe/errors/errorcode/ProductErrorCode.java
src/main/java/com/foru/freebe/errors/errorcode/ProductImageErrorCode.java
src/main/java/com/foru/freebe/errors/errorcode/ProfileErrorCode.java
src/main/java/com/foru/freebe/notice/service/PhotographerNoticeService.java
src/main/java/com/foru/freebe/product/controller/PhotographerProductController.java
src/main/java/com/foru/freebe/product/service/PhotographerProductService.java
src/main/java/com/foru/freebe/profile/service/PhotographerProfileService.java
src/main/java/com/foru/freebe/profile/service/ProfileService.java
src/main/java/com/foru/freebe/reservation/service/CustomerReservationService.java
src/test/java/com/foru/freebe/profile/service/ProfileServiceTest.java

- 상품 등록 시 등록된 사진이 없는지에 대한 검증을 controller에서 진행하도록 어노테이션 옵션 추가 (기존 검증 로직을 대체할 수 있어 검증 로직은 삭제했습니다.)
- 모호한 에러메시지명 수정
- Profile에서 MEMBER_NOT_FOUND -> PROFILE_NOT_FOUND
- TITLE_DUPLICATE를 NOTICE, LINK 엔티티에 맞게 명확한 의미로 수정
- 서비스 운영 상 크리티컬한 오류여서 분석이 필요한 에러의 HttpStatus를 500으로 수정 - 뉴렐릭에서 500번 에러를 트래킹하여 slack으로 알림을 받아 분석하기 위함입니다.
- AMAZON_S3_EXCEPTION: 이미지 업로드 하는 과정에서 에러가 발생한 경우
- PROFILE_NAME_NOT_FOUND: 알림톡이 정상적으로 전송되지 않은 경우 / 사진작가의 예약 페이지가 정상적으로 조회되지 않은 경우
- PROFILE_NOT_FOUND: 예약이 정상적으로 이뤄지지 않은 경우    
- 어떤 경우에 에러 메시지를 500번으로 변경해야 할지에 대한 고민이 있었습니다. 무조건 서버에서 조회하는 모든 경우를 500번으로 수정하기에는 우리가 예상한 정상적인 로직에 대한 400번대 에러는 굳이 알림을 받아 분석할 필요를 느끼지 못했습니다.(제가 기준을 명확하게 찾지 못한 것 같기도 해요🥲) 현재 변경된 에러들의 기준이 명확하지 않다고 느껴지면 코멘트 남겨주세요!
- 에러메시지들이 위에서 설명한 경우를 포함하고 있기 때문에 500번 에러로 수정하였고, 해당 에러메시지를 다른 경우에 사용하는 …

[FU-334] 에러메시지 개선

---

src/main/java/com/foru/freebe/errors/handler/GlobalExceptionHandler.java
src/main/java/com/foru/freebe/product/entity/Product.java

- 동일한 제목의 상품 두 개가 중복 등록되는 문제가 발생했습니다.
<br>
- 상품등록 API 요청을 처리하는 과정에서 S3에 이미지를 업로드하는데 많은 시간이 소요되어 클라이언트 측에서 해당 요청을 타임아웃으로 간주하는 문제가 발생했습니다. 타임아웃이 발생하면서 고객에게 상품등록 재시도를 권유하는 메시지가 노출됨과 동시에 상품등록 버튼이 재차 활성화되면서, 서버에서 첫 요청에 대한 처리가 끝나기 전에  동일한 상품등록 요청이 중복되어 들어오게 되었습니다. 
- 트랜잭션으로 묶여 있는 경우 트랜잭션이 종료되는 시점에 커밋이 자동으로 이뤄지고 DB에 변경내역이 반영됩니다. 트랜잭션 A가 종료되기 전에 이미 10초 이상의 시간이 소요됐고, 트랜잭션 B가 시작됐을 때는 변경내역이 DB에 반영되기 전이었으므로 B요청에서 상품 제목의 중복여부를 검사하는 로직도 문제 없이 통과하게 되었습니다. 
<br>
- 기존 코드에서 상품 제목의 중복여부 검사는 트랜잭션이 시작되자마자 이뤄지는데, 트랜잭션 시작 시점과 종료 시점 사이에 상당한 텀이 있으므로 (상품 이미지 업로드에 많은 시간이 소요되기 때문) 실제로 상품이 등록되는 트랜잭션 종료시점에는 상품 제목의 유일성을 보장하기 어려워진 것이 문제라고 볼 수 있습니다.
- 따라서 트랜잭션이 종료되고 변경내역이 DB에 반영되는 시점에도 상품 제목의 중복여부를 검증해줄 필요성이 있습니다. 이는 상품 테이블의 (member_id, product_title)을 결합한 unique 제약조건을 걸어 DB 단에서 유일성이 보장되도록 조치했습니다.
<br>
1. unique 제약조건을 …

[FU-339] 상품 중복등록 방지를 위한 제약조건 추가

---

src/main/java/com/foru/freebe/errors/handler/GlobalExceptionHandler.java
src/main/java/com/foru/freebe/product/entity/Product.java

v1.1.4
* feat: Product 테이블 unique 제약조건 추가
- product title, member_id를 결합해 제약조건으로 설정하였음
* feat: DataIntegrityViolationException 예외 처리
- 제약 조건을 위반(상품 제목 중복 등록 등)했을 경우 예외 처리하기 위함

[v1.1.4] QA 진행

---

src/main/java/com/foru/freebe/errors/errorcode/ScheduleErrorCode.java
src/main/java/com/foru/freebe/member/entity/ScheduleUnit.java
src/main/java/com/foru/freebe/schedule/repository/DailyScheduleRepository.java
src/main/java/com/foru/freebe/schedule/service/BaseScheduleService.java
src/main/java/com/foru/freebe/schedule/service/DailyScheduleService.java
src/main/java/com/foru/freebe/schedule/service/DailyScheduleValidator.java
src/test/java/com/foru/freebe/schedule/DailyScheduleServiceTest.java
src/test/java/com/foru/freebe/schedule/service/BaseScheduleServiceTest.java
src/test/java/com/foru/freebe/schedule/service/DailyScheduleServiceTest.java
src/test/java/com/foru/freebe/schedule/service/DailyScheduleValidatorTest.java

<br>
이번 PR에서는 스케줄 유형에 따른 위계 구조를 명확히 하고, 같은 레벨의 스케줄 간에만 충돌 여부를 검증하도록 로직을 보완했습니다.
또한, 날짜별 스케줄은 기본 스케줄 단위와 일치하도록 설정했습니다.
- 스케줄 위계 구조 개선
|--- 예약 확정 스케줄
|-- 추가오픈 or 예약 중지 스케줄
|- 기본 스케줄
- `추가오픈`과 `예약 중지` 간에 충돌 여부를 검증
- `예약 확정` 스케줄은 동일한 유형의 `예약 확정` 스케줄과만 충돌 여부를 검증
- 날짜별 스케줄 로직 보완
- 기본 스케줄 단위가 `60분`이면, 시작/종료 시간은 반드시 **정시**여야 함.
- 기본 스케줄 단위가 `30분`이면, 시작/종료 시간은 **정시 또는 30분 단위**여야 함.
<br>
날짜별 스케줄의 등록/수정 요청 시, 요청 객체의 유효성 검증과 비즈니스 요구사항을 해치지 않는지 검증하는 과정이 복잡해짐에 따라, 자연스럽게 `DailyScheduleService`도 무거워졌습니다. `DailyScheduleService`는 스케줄 생성, 조회, 삭제, 검증 등 다양한 책임을 가지게 되었습니다.😓
점점 `DailyScheduleService`에 메서드를 추가하는 과정이 부담스러워지고, 테스트 코드를 작성하는 데도 부담이 커지는 것을 느껴 리팩터링을 고려하게 되었습니다. 그 중에서도 검증 로직을 전담 클래스로 분리하여 API 요청으로부터 호출되는 서비스 클래스를 간결하게 관리하고, 단일 책임 원칙(SRP)을 따르는 방향을 고려했습니다. 물론 클래스를 분리함에 따라 테스트 코드도 연쇄적으로 수정해야 했지만, 오히려 아래와 …

[FU-357] 날짜별 스케줄 검증로직 개선 및 리팩터링
